version: "2"

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - contextcheck
    - durationcheck
    - errcheck
    - errname
    - errorlint
    # configure it properly, see https://github.com/securego/gosec#available-rules
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - prealloc
    - predeclared
    - reassign
    - revive
    - rowserrcheck
    - staticcheck
    - tagliatelle
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign

  exclusions:
    rules:
      # Exclude some linters from running on tests files.
      - path: _test\.go
        linters:
          - gosec
