apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    app: hello-world
  annotations:
spec:
  containers:
    - name: hello-world
      image: quay.io/fedora/fedora:43
      env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: test-secret
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: test-secret
              key: password
      command:
        - sleep
        - "36000"
      securityContext:
        privileged: false
        seccompProfile:
          type: RuntimeDefault
